### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.config/jekyll-utils/config.toml'

### ISSUE THREAD

**Issue by queirozfcom** [queirozfcom/jekyll-utils#1]
This error happens if you try to run `jk-config-set-editor` or any other commands after installing the project (on a computer that never before had it - that must be the reason why the file isn't there yet)

**Comment by queirozfcom** [comment]
Workaround: `touch ~/.config/jekyll-utils/config.toml`

In MacOS it's another path: `/Users/felipe.almeida/Library/Application Support/jekyll-utils/config.toml`

**Comment by queirozfcom** [comment]
Also happens when you just cloned/installed the project and you try to run `jk-edit`

$ jk-edit python datetime
Traceback (most recent call last):
  File "/Users/felipe.almeida/miniconda3/bin/jk-edit", line 11, in <module>
    load_entry_point('jekyllutils', 'console_scripts', 'jk-edit')()
  File "/Users/felipe.almeida/miniconda3/lib/python3.6/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/Users/felipe.almeida/miniconda3/lib/python3.6/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/Users/felipe.almeida/miniconda3/lib/python3.6/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/felipe.almeida/miniconda3/lib/python3.6/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/Users/felipe.almeida/dev/jekyll-utils/jekyllutils/managers.py", line 17, in edit_post
    path_to_posts_directory = resolve_path(get_posts_path())
  File "/Users/felipe.almeida/dev/jekyll-utils/jekyllutils/helpers/configs.py", line 11, in get_posts_path
    return _get_config("posts-path")
  File "/Users/felipe.almeida/dev/jekyll-utils/jekyllutils/helpers/configs.py", line 66, in _get_config
    with open(_get_path_to_config_file()) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/felipe.almeida/Library/Application Support/jekyll-utils/config.toml'

**Comment by queirozfcom** [comment]
**TODO** create a new config file if it doesn't exist

**Comment by queirozfcom** [comment]
in MacOS: 

```
Traceback (most recent call last):
  File "/Users/felipe.almeida/.pyenv/versions/3.9.16/bin/jk-edit", line 33, in <module>
    sys.exit(load_entry_point('jekyllutils', 'console_scripts', 'jk-edit')())
  File "/Users/felipe.almeida/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/Users/felipe.almeida/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/Users/felipe.almeida/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/felipe.almeida/.pyenv/versions/3.9.16/lib/python3.9/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/Users/felipe.almeida/dev/jekyll-utils/jekyllutils/managers.py", line 18, in edit_post
    path_to_posts_directory = resolve_path(get_posts_path())
  File "/Users/felipe.almeida/dev/jekyll-utils/jekyllutils/helpers/configs.py", line 11, in get_posts_path
    return _get_config("posts-path")
  File "/Users/felipe.almeida/dev/jekyll-utils/jekyllutils/helpers/configs.py", line 66, in _get_config
    with open(_get_path_to_config_file()) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/felipe.almeida/Library/Application Support/jekyll-utils/config.toml'
```
